### ISSUE TITLE
 Unable to Save Emergency Contact Numbers

### ISSUE THREAD

**Issue by Suryansh1720001** [soumenkp2/Pehchaan#9] opened 2024-01-12 05:18 UTC
**Description:**

I've identified a bug in the Emergency Fragment where the application fails to save emergency contact numbers properly. Despite following the existing code structure, the numbers aren't persisting as expected. I'm planning to take ownership of this issue and work on resolving it. Open to collaboration and any insights from the community. Let's ensure users can seamlessly save their emergency contact numbers through the Emergency Fragment.

Assign this issue to me @soumenkp2 @Shivgupta1031

**Comment by soumenkp2** [comment] 2024-01-12 08:58
Thanks for bringing out the bug inside of the Emergency Section. 
The issue is now labeled with proper tags and assigned to you. 
Give it a go!

**Comment by soumenkp2** [comment] 2024-01-12 15:27
Hi @Suryansh1720001 , 
This is regarding the bug you have identified on the inability to save emergency contacts. 
Unfortunately, I am not able to reproduce any kind of bug in saving the emergency contacts. 
Can you please let me know the steps that I should follow to reproduce the bug or a reference video can work too?

**Comment by Suryansh1720001** [comment] 2024-01-12 15:42
Hello @soumenkp2,

Actually, when I was exploring the application, I had trouble clicking on "Enter num1" in the emergency section. I thought it was a bug and reported it. However, after you assigned the issue to me, I realized that the code actually requires clicking on the right side edit image to enable the "Enter num1" input.
Upon realizing this, I proceeded to take additional steps to ensure that my contribution to this issue was not wasted.
- I modified the functionality of the edit view.
- I ensured that the phone edit view only accepts numeric input.
- I formatted the code for better readability.

I hope my point is clear now and if not, please let me know. And also I apologize for any confusion earlier.

**Comment by Suryansh1720001** [comment] 2024-01-13 07:54
@soumenkp2 
Kindly, Check this one.

**Comment by soumenkp2** [comment] 2024-01-13 15:46
Hi @Suryansh1720001 , 
Thanks for the clarification. 
I have added the comments in the PR.

**Closed as completed** 2024-01-14 08:58 UTC
Labels: easy, iwoc2024
